export const STORAGE_KEY = "krykhta-state-v1";
export const LOCAL_DB_STATE_KEY = "state";
export const STARTER_DATA_VERSION = 2;
export const availableViews = ["home", "menu", "shopping", "pantry"];

const baseState = {
  dataVersion: STARTER_DATA_VERSION,
  activeView: "home",
  priority: "balance",
  selectedDay: 0,
  budget: 420,
  shopping: [
    { id: 1, name: "Куряче філе", amount: "500 г", price: 96, category: "М’ясо та риба", checked: false, urgent: true },
    { id: 2, name: "Йогурт натуральний", amount: "200 г", price: 31, category: "Молочне", checked: false, urgent: false },
    { id: 3, name: "Печериці", amount: "300 г", price: 42, category: "Овочі", checked: false, urgent: false },
    { id: 4, name: "Помідори", amount: "500 г", price: 48, category: "Овочі", checked: true, urgent: false },
    { id: 5, name: "Зелень", amount: "1 пучок", price: 22, category: "Овочі", checked: false, urgent: false },
    { id: 6, name: "Булгур", amount: "400 г", price: 39, category: "Бакалія", checked: true, urgent: false },
    { id: 7, name: "Хліб цільнозерновий", amount: "1 шт", price: 36, category: "Бакалія", checked: false, urgent: false },
  ],
  pantry: [
    { id: 1, name: "Яйця", amount: "6 шт", emoji: "🥚", low: false },
    { id: 2, name: "Гречка", amount: "350 г", emoji: "🌾", low: false },
    { id: 3, name: "Цибуля", amount: "2 шт", emoji: "🧅", low: true },
    { id: 4, name: "Морква", amount: "3 шт", emoji: "🥕", low: false },
    { id: 5, name: "Сир", amount: "80 г", emoji: "🧀", low: true },
    { id: 6, name: "Картопля", amount: "1,2 кг", emoji: "🥔", low: false },
    { id: 7, name: "Квасоля", amount: "1 банка", emoji: "🫘", low: false },
  ],
  meals: [
    {
      id: 1,
      day: "Сьогодні",
      shortDay: "Пн",
      date: 19,
      title: "Курка з булгуром",
      time: 25,
      price: 78,
      emoji: "🍲",
      tag: "Найкращий баланс",
      ingredients: [
        { name: "Булгур", amount: "180 г", missing: false },
        { name: "Морква", amount: "1 шт", missing: false },
        { name: "Цибуля", amount: "1 шт", missing: false },
        { name: "Куряче філе", amount: "300 г", missing: true },
        { name: "Йогурт", amount: "100 г", missing: true },
      ],
    },
    {
      id: 2,
      day: "Завтра",
      shortDay: "Вт",
      date: 20,
      title: "Гречка з грибами",
      time: 18,
      price: 44,
      emoji: "🍄",
      tag: "Найдешевше",
      ingredients: [
        { name: "Гречка", amount: "180 г", missing: false },
        { name: "Цибуля", amount: "1 шт", missing: false },
        { name: "Печериці", amount: "250 г", missing: true },
        { name: "Йогурт", amount: "80 г", missing: true },
      ],
    },
    {
      id: 3,
      day: "Середа",
      shortDay: "Ср",
      date: 21,
      title: "Теплий салат з квасолею",
      time: 12,
      price: 52,
      emoji: "🥗",
      tag: "Найшвидше",
      ingredients: [
        { name: "Квасоля", amount: "1 банка", missing: false },
        { name: "Морква", amount: "1 шт", missing: false },
        { name: "Помідори", amount: "2 шт", missing: false },
        { name: "Зелень", amount: "пів пучка", missing: true },
      ],
    },
    {
      id: 4,
      day: "Четвер",
      shortDay: "Чт",
      date: 22,
      title: "Картопляна фритата",
      time: 22,
      price: 39,
      emoji: "🍳",
      tag: "З того, що є",
      ingredients: [
        { name: "Яйця", amount: "4 шт", missing: false },
        { name: "Картопля", amount: "400 г", missing: false },
        { name: "Цибуля", amount: "1 шт", missing: false },
        { name: "Сир", amount: "60 г", missing: false },
      ],
    },
    {
      id: 5,
      day: "П’ятниця",
      shortDay: "Пт",
      date: 23,
      title: "Овочевий суп",
      time: 30,
      price: 46,
      emoji: "🥣",
      tag: "На два дні",
      ingredients: [
        { name: "Картопля", amount: "500 г", missing: false },
        { name: "Морква", amount: "2 шт", missing: false },
        { name: "Цибуля", amount: "1 шт", missing: false },
        { name: "Зелень", amount: "пів пучка", missing: true },
      ],
    },
    {
      id: 6,
      day: "Субота",
      shortDay: "Сб",
      date: 24,
      title: "Сирні гарячі тости",
      time: 10,
      price: 51,
      emoji: "🥪",
      tag: "Дуже швидко",
      ingredients: [
        { name: "Хліб", amount: "4 скибки", missing: true },
        { name: "Сир", amount: "80 г", missing: false },
        { name: "Помідори", amount: "1 шт", missing: false },
      ],
    },
    {
      id: 7,
      day: "Неділя",
      shortDay: "Нд",
      date: 25,
      title: "Запечена картопля",
      time: 35,
      price: 43,
      emoji: "🥔",
      tag: "Мінімум зусиль",
      ingredients: [
        { name: "Картопля", amount: "700 г", missing: false },
        { name: "Йогурт", amount: "120 г", missing: true },
        { name: "Зелень", amount: "пів пучка", missing: true },
      ],
    },
  ],
  productCatalog: [],
  recipeCatalog: [],
};

export const cookingGuides = {
  "Курка з булгуром": [
    "Промий булгур. Залий його водою у співвідношенні один до двох, трохи посоли й вари 12–15 хвилин.",
    "Наріж куряче філе невеликими шматочками, а моркву та цибулю — кубиками.",
    "Обсмаж курку 5–6 хвилин на добре розігрітій пательні.",
    "Додай овочі та готуй ще 5 хвилин, поки вони не стануть м’якими.",
    "Змішай курку з булгуром. Подай з ложкою натурального йогурту.",
  ],
  "Гречка з грибами": [
    "Промий гречку, залий двома частинами води та вари під кришкою 15 хвилин.",
    "Наріж цибулю й печериці.",
    "Обсмаж цибулю 2 хвилини, додай гриби та готуй ще 6–7 хвилин.",
    "Змішай гриби з готовою гречкою, посоли й додай ложку йогурту перед подачею.",
  ],
  "Теплий салат з квасолею": [
    "Злий рідину з квасолі та промий її.",
    "Наріж моркву тонкою соломкою, а помідори — часточками.",
    "Прогрій квасолю з морквою на пательні 5 хвилин.",
    "Зніми з вогню, додай помідори, зелень, сіль та трохи олії.",
  ],
  "Картопляна фритата": [
    "Наріж картоплю тонкими скибками, а цибулю — півкільцями.",
    "Обсмаж картоплю з цибулею під кришкою 10 хвилин.",
    "Збий яйця з дрібкою солі та залий ними картоплю.",
    "Посип сиром і готуй під кришкою ще 7–8 хвилин на малому вогні.",
  ],
  "Овочевий суп": [
    "Постав 1,5 літра води на вогонь.",
    "Наріж картоплю кубиками й вари 10 хвилин.",
    "Додай нарізані моркву та цибулю, посоли й вари ще 12–15 хвилин.",
    "Вимкни вогонь, додай зелень і дай супу постояти 5 хвилин.",
  ],
  "Сирні гарячі тости": [
    "Наріж помідор тонкими скибками.",
    "Виклади на хліб сир і помідор.",
    "Підсмаж тости на сухій пательні під кришкою по 3–4 хвилини з кожного боку.",
  ],
  "Запечена картопля": [
    "Розігрій духовку до 210 градусів.",
    "Добре помий картоплю, наріж часточками та змішай із сіллю й ложкою олії.",
    "Запікай 30–35 хвилин, один раз перемішавши.",
    "Змішай йогурт із зеленню та подай як соус.",
  ],
};

const starterProductCatalog = [
  { id: 101, name: "Рис", amount: "500 г", price: 48, category: "Бакалія", emoji: "🍚" },
  { id: 102, name: "Макарони", amount: "500 г", price: 46, category: "Бакалія", emoji: "🍝" },
  { id: 103, name: "Вівсянка", amount: "500 г", price: 42, category: "Бакалія", emoji: "🥣" },
  { id: 104, name: "Сочевиця", amount: "400 г", price: 57, category: "Бакалія", emoji: "🫘" },
  { id: 105, name: "Кускус", amount: "400 г", price: 55, category: "Бакалія", emoji: "🌾" },
  { id: 106, name: "Борошно", amount: "1 кг", price: 38, category: "Бакалія", emoji: "🌾" },
  { id: 107, name: "Олія", amount: "850 мл", price: 72, category: "Бакалія", emoji: "🫗" },
  { id: 108, name: "Томати консервовані", amount: "1 банка", price: 54, category: "Бакалія", emoji: "🥫" },
  { id: 109, name: "Нут", amount: "1 банка", price: 49, category: "Бакалія", emoji: "🫛" },
  { id: 110, name: "Тунець", amount: "1 банка", price: 79, category: "М’ясо та риба", emoji: "🐟" },
  { id: 111, name: "Риба біла", amount: "500 г", price: 145, category: "М’ясо та риба", emoji: "🐟" },
  { id: 112, name: "Фарш курячий", amount: "500 г", price: 105, category: "М’ясо та риба", emoji: "🍗" },
  { id: 113, name: "Молоко", amount: "900 мл", price: 48, category: "Молочне", emoji: "🥛" },
  { id: 114, name: "Сметана", amount: "300 г", price: 44, category: "Молочне", emoji: "🥛" },
  { id: 115, name: "Кисломолочний сир", amount: "350 г", price: 78, category: "Молочне", emoji: "🧀" },
  { id: 116, name: "Вершки", amount: "200 мл", price: 52, category: "Молочне", emoji: "🥛" },
  { id: 117, name: "Банани", amount: "1 кг", price: 62, category: "Фрукти", emoji: "🍌" },
  { id: 118, name: "Яблука", amount: "1 кг", price: 45, category: "Фрукти", emoji: "🍎" },
  { id: 119, name: "Часник", amount: "1 головка", price: 14, category: "Овочі", emoji: "🧄" },
  { id: 120, name: "Перець солодкий", amount: "500 г", price: 69, category: "Овочі", emoji: "🫑" },
  { id: 121, name: "Кабачок", amount: "1 шт", price: 39, category: "Овочі", emoji: "🥒" },
  { id: 122, name: "Броколі", amount: "400 г", price: 72, category: "Овочі", emoji: "🥦" },
  { id: 123, name: "Гарбуз", amount: "1 кг", price: 38, category: "Овочі", emoji: "🎃" },
  { id: 124, name: "Огірки", amount: "500 г", price: 52, category: "Овочі", emoji: "🥒" },
  { id: 125, name: "Капуста", amount: "1 кг", price: 34, category: "Овочі", emoji: "🥬" },
  { id: 126, name: "Лаваш", amount: "2 шт", price: 39, category: "Хліб", emoji: "🫓" },
  { id: 127, name: "Лимон", amount: "1 шт", price: 18, category: "Фрукти", emoji: "🍋" },
  { id: 128, name: "Заморожені овочі", amount: "400 г", price: 62, category: "Заморожене", emoji: "🥦" },
  { id: 129, name: "Кукурудза", amount: "1 банка", price: 43, category: "Бакалія", emoji: "🌽" },
  { id: 130, name: "Соєвий соус", amount: "250 мл", price: 58, category: "Соуси", emoji: "🥫" },
];

const starterRecipeCatalog = [
  {
    id: 1001,
    title: "Рис з овочами та яйцем",
    time: 18,
    price: 45,
    emoji: "🍚",
    tag: "Швидка пательня",
    ingredients: [
      { name: "Рис", amount: "180 г" },
      { name: "Заморожені овочі", amount: "250 г" },
      { name: "Яйця", amount: "2 шт" },
      { name: "Соєвий соус", amount: "2 ст. ложки" },
    ],
    steps: [
      "Відвари рис до готовності та дай йому трохи охолонути.",
      "Обсмаж заморожені овочі 6–7 хвилин на великому вогні.",
      "Посунь овочі вбік, розбий яйця й швидко перемішай.",
      "Додай рис і соєвий соус, прогрій усе разом ще 3 хвилини.",
    ],
  },
  {
    id: 1002,
    title: "Паста з тунцем",
    time: 15,
    price: 69,
    emoji: "🍝",
    tag: "15 хвилин",
    ingredients: [
      { name: "Макарони", amount: "200 г" },
      { name: "Тунець", amount: "1 банка" },
      { name: "Томати консервовані", amount: "200 г" },
      { name: "Часник", amount: "1 зубчик" },
    ],
    steps: [
      "Відвари макарони у підсоленій воді.",
      "Прогрій на пательні подрібнений часник і консервовані томати.",
      "Додай тунець без рідини та готуй 3 хвилини.",
      "Змішай соус із макаронами та подавай.",
    ],
  },
  {
    id: 1003,
    title: "Сочевичне карі",
    time: 25,
    price: 54,
    emoji: "🍛",
    tag: "Ситно без м’яса",
    ingredients: [
      { name: "Сочевиця", amount: "200 г" },
      { name: "Томати консервовані", amount: "250 г" },
      { name: "Цибуля", amount: "1 шт" },
      { name: "Морква", amount: "1 шт" },
    ],
    steps: [
      "Промий сочевицю та постав варитися у двох частинах води.",
      "Обсмаж нарізані цибулю й моркву 5 хвилин.",
      "Додай томати, карі або улюблені спеції та тушкуй 5 хвилин.",
      "Змішай із сочевицею й готуй до м’якості ще 8–10 хвилин.",
    ],
  },
  {
    id: 1004,
    title: "Вівсянка з бананом",
    time: 8,
    price: 31,
    emoji: "🥣",
    tag: "Найшвидший сніданок",
    ingredients: [
      { name: "Вівсянка", amount: "80 г" },
      { name: "Молоко", amount: "250 мл" },
      { name: "Банани", amount: "1 шт" },
    ],
    steps: [
      "Залий вівсянку молоком і вари 5–6 хвилин, помішуючи.",
      "Розімни половину банана та додай у кашу.",
      "Наріж решту банана зверху й подавай.",
    ],
  },
  {
    id: 1005,
    title: "Шакшука",
    time: 20,
    price: 49,
    emoji: "🍳",
    tag: "Одна пательня",
    ingredients: [
      { name: "Яйця", amount: "4 шт" },
      { name: "Томати консервовані", amount: "300 г" },
      { name: "Перець солодкий", amount: "1 шт" },
      { name: "Цибуля", amount: "1 шт" },
    ],
    steps: [
      "Обсмаж нарізані цибулю та перець 5 хвилин.",
      "Додай томати, сіль і спеції та тушкуй 7 хвилин.",
      "Зроби заглиблення, вбий яйця й накрий кришкою.",
      "Готуй 5–6 хвилин, щоб білок схопився.",
    ],
  },
  {
    id: 1006,
    title: "Кускус з нутом",
    time: 12,
    price: 52,
    emoji: "🥗",
    tag: "Без варіння",
    ingredients: [
      { name: "Кускус", amount: "180 г" },
      { name: "Нут", amount: "1 банка" },
      { name: "Огірки", amount: "1 шт" },
      { name: "Помідори", amount: "2 шт" },
      { name: "Лимон", amount: "пів шт" },
    ],
    steps: [
      "Залий кускус окропом, накрий і залиш на 7 хвилин.",
      "Промий нут, наріж огірок і помідори.",
      "Розпуши кускус виделкою та змішай з овочами й нутом.",
      "Заправ лимонним соком, олією та сіллю.",
    ],
  },
  {
    id: 1007,
    title: "Крем-суп з гарбуза",
    time: 35,
    price: 47,
    emoji: "🎃",
    tag: "На два обіди",
    ingredients: [
      { name: "Гарбуз", amount: "700 г" },
      { name: "Картопля", amount: "250 г" },
      { name: "Морква", amount: "1 шт" },
      { name: "Вершки", amount: "100 мл" },
    ],
    steps: [
      "Наріж гарбуз, картоплю та моркву кубиками.",
      "Залий овочі водою до рівня продуктів і вари 25 хвилин.",
      "Збий суп блендером до однорідності.",
      "Додай вершки, сіль і прогрій ще 2 хвилини.",
    ],
  },
  {
    id: 1008,
    title: "Салат з тунцем і квасолею",
    time: 10,
    price: 62,
    emoji: "🥗",
    tag: "Без плити",
    ingredients: [
      { name: "Тунець", amount: "1 банка" },
      { name: "Квасоля", amount: "1 банка" },
      { name: "Кукурудза", amount: "пів банки" },
      { name: "Огірки", amount: "1 шт" },
    ],
    steps: [
      "Злий рідину з тунця, квасолі та кукурудзи.",
      "Наріж огірок невеликими кубиками.",
      "Змішай усе, додай сіль, перець і трохи олії.",
    ],
  },
  {
    id: 1009,
    title: "Лаваш з куркою й овочами",
    time: 20,
    price: 76,
    emoji: "🌯",
    tag: "Зручно із собою",
    ingredients: [
      { name: "Лаваш", amount: "2 шт" },
      { name: "Куряче філе", amount: "250 г" },
      { name: "Капуста", amount: "150 г" },
      { name: "Огірки", amount: "1 шт" },
      { name: "Йогурт", amount: "100 г" },
    ],
    steps: [
      "Наріж курку смужками й обсмаж 8–10 хвилин.",
      "Тонко нашаткуй капусту та наріж огірок.",
      "Змасти лаваш йогуртом, виклади начинку й загорни.",
      "Підрум’янь лаваш по 2 хвилини з кожного боку.",
    ],
  },
  {
    id: 1010,
    title: "Сирники",
    time: 25,
    price: 58,
    emoji: "🥞",
    tag: "Домашній сніданок",
    ingredients: [
      { name: "Кисломолочний сир", amount: "350 г" },
      { name: "Яйця", amount: "1 шт" },
      { name: "Борошно", amount: "70 г" },
      { name: "Сметана", amount: "80 г" },
    ],
    steps: [
      "Змішай сир, яйце, дрібку солі та половину борошна.",
      "Сформуй сирники й обкачай у решті борошна.",
      "Обсмаж на малому вогні по 4–5 хвилин з кожного боку.",
      "Подай зі сметаною.",
    ],
  },
  {
    id: 1011,
    title: "Запечена риба з броколі",
    time: 30,
    price: 98,
    emoji: "🐟",
    tag: "Легка вечеря",
    ingredients: [
      { name: "Риба біла", amount: "400 г" },
      { name: "Броколі", amount: "300 г" },
      { name: "Лимон", amount: "пів шт" },
      { name: "Йогурт", amount: "100 г" },
    ],
    steps: [
      "Розігрій духовку до 200 градусів.",
      "Посоли рибу, скропи лимоном і виклади у форму.",
      "Поруч розклади броколі та запікай 20–25 хвилин.",
      "Подай з йогуртовим соусом.",
    ],
  },
  {
    id: 1012,
    title: "Паста з грибами у вершках",
    time: 20,
    price: 63,
    emoji: "🍄",
    tag: "Комфортна вечеря",
    ingredients: [
      { name: "Макарони", amount: "200 г" },
      { name: "Печериці", amount: "250 г" },
      { name: "Вершки", amount: "150 мл" },
      { name: "Цибуля", amount: "1 шт" },
    ],
    steps: [
      "Відвари макарони до стану аль денте.",
      "Обсмаж цибулю та нарізані гриби 7–8 хвилин.",
      "Додай вершки, сіль і прогрій 3 хвилини.",
      "Змішай соус із макаронами.",
    ],
  },
];

export const defaultState = {
  ...baseState,
  productCatalog: starterProductCatalog,
  recipeCatalog: starterRecipeCatalog,
};
